# Use the official Golang image as a builder
FROM golang:1.24 AS builder

# Set the working directory
WORKDIR /app

# Copy go.mod and go.sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the rest of the application code
COPY . .

# Build the Go application
RUN go build -o main ./cmd/main.go

# # Use a minimal image to run the app
# FROM alpine:latest

# # Set the working directory
# WORKDIR /app

# # Copy the compiled binary from the builder stage
# COPY --from=builder /app/main .

# Expose the application port
EXPOSE 8080

# Command to run the application
CMD ["./main"]